name: CI Frontend and Backend

on:
  pull_request:
    branches: [development]
    paths:
      - "frontend/**"
      - "backend/**"
  workflow_dispatch: {}

# Needed for OIDC and for checking out code
permissions:
  contents: read
  id-token: write

jobs:
  detect:
    name: Detect changed paths
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend:  ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  build_frontend:
    if: needs.detect.outputs.frontend == 'true'
    needs: detect
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (Replace with your real frontend build if needed)
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install & build (frontend)
        working-directory: frontend
        run: |
          npm ci || npm install
          npm run build || echo "demo build only"

  build_backend:
    if: needs.detect.outputs.backend == 'true'
    needs: detect
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (Replace with your real backend build if needed)
      - name: .NET setup (example)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build (backend)
        working-directory: backend
        run: |
          dotnet restore || true
          dotnet build -c Release || echo "demo build only"
