name: CI Frontend and Backend

on:
  pull_request:
    branches: [development]
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write
  packages: write

env:
  ACR_LOGIN: ${{ vars.ACR_LOGIN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect changed paths
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend:  ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  build_frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: changes
    if: |
      (github.event_name == 'pull_request' && needs.changes.outputs.frontend == 'true') ||
      (github.event_name == 'push' && github.ref_name == 'main' && needs.changes.outputs.frontend == 'true')
    steps:
      - uses: actions/checkout@v4
      - run: echo Frontend checks passed
      - uses: docker/setup-buildx-action@v3
      - name: Azure login
        if: github.event_name == 'push' && github.ref_name == 'main'
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
      - name: ACR login
        if: github.event_name == 'push' && github.ref_name == 'main'
        run: |
          test -n "${ACR_LOGIN}" || { echo ACR_LOGIN not set; exit 0; }
          az acr login --name ${ACR_LOGIN%%.*}
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          tags: |
            ${{ env.ACR_LOGIN }}/frontend:${{ github.sha }}
            ${{ env.ACR_LOGIN }}/frontend:latest
          push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build_backend:
    name: Build Backend (monolith)
    runs-on: ubuntu-latest
    needs: changes
    if: |
      (github.event_name == 'pull_request' && needs.changes.outputs.backend == 'true') ||
      (github.event_name == 'push' && github.ref_name == 'main' && needs.changes.outputs.backend == 'true')
    steps:
      - uses: actions/checkout@v4
      - run: echo Backend checks passed
      - uses: docker/setup-buildx-action@v3
      - name: Azure login
        if: github.event_name == 'push' && github.ref_name == 'main'
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
      - name: ACR login
        if: github.event_name == 'push' && github.ref_name == 'main'
        run: |
          test -n "${ACR_LOGIN}" || { echo ACR_LOGIN not set; exit 0; }
          az acr login --name ${ACR_LOGIN%%.*}
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          tags: |
            ${{ env.ACR_LOGIN }}/week08/backend:${{ github.sha }}
            ${{ env.ACR_LOGIN }}/week08/backend:latest
          push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
