name: CI Frontend and Backend

on:
  pull_request:
    branches: [development]
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write
  packages: write

env:
  ACR_LOGIN: ${{ vars.ACR_LOGIN }}
