# make a safety branch
git switch -c fix-workflows

# restore backend_cd.yml from the commit before your change
git log -- .github/workflows/backend_cd.yml
# copy the SHA just BEFORE your edit, then:
git checkout <GOOD_SHA> -- .github/workflows/backend_cd.yml

# ensure CI file exists with your CI content
# (open editor and paste; or if it already exists, skip)
notepad .github/workflows/backend_ci.yml

git add .github/workflows/backend_cd.yml .github/workflows/backend_ci.yml
git commit -m "Restore backend_cd.yml and place CI workflow in backend_ci.yml"
git push -u origin fix-workflows
