name: Backend CI - Test, Build & (conditionally) Push

on:
  pull_request:
    branches: [development]
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write
  packages: write

env:
  # Example: s722acrXXXXX.azurecr.io (set this in repo "Actions → Variables")
  ACR_LOGIN: ${{ vars.ACR_LOGIN }}

jobs:
  test_build_push:
    name: Build backend services
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Detect changed backend paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            order:   'backend/order/**'
            product: 'backend/product/**'

      - uses: docker/setup-buildx-action@v3

      # Only authenticate to Azure on push to main
      - name: Azure login (service principal)
        if: github.event_name == 'push' && github.ref_name == 'main'
        uses: azure/login@v2
        with:
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}

      # Only log in to ACR on push to main (and only if ACR_LOGIN is set)
      - name: ACR login
        if: github.event_name == 'push' && github.ref_name == 'main' && env.ACR_LOGIN != ''
        run: az acr login --name ${ACR_LOGIN%%.*}

      # Order service
      - name: Build order-service image
        if: steps.filter.outputs.order == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./backend/order
          tags: |
            ${{ env.ACR_LOGIN }}/week08/order-service:${{ github.sha }}
            ${{ env.ACR_LOGIN }}/week08/order-service:latest
          push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Product service
      - name: Build product-service image
        if: steps.filter.outputs.product == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./backend/product
          tags: |
            ${{ env.ACR_LOGIN }}/week08/product-service:${{ github.sha }}
            ${{ env.ACR_LOGIN }}/week08/product-service:latest
          push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
