name: Backend CD - Deploy to AKS

on:
  workflow_run:
    workflows: ["CI Frontend and Backend"]
    types: [completed]
    branches: [main]

concurrency:
  group: cd-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && vars.AZURE_CLIENT_ID && vars.AZURE_TENANT_ID && vars.AZURE_SUBSCRIPTION_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Show ACR images
        run: |
          : "${ACR_LOGIN_SERVER?Need env ACR_LOGIN_SERVER (e.g. wk08acr123.azurecr.io)}"
          az acr repository list --name "${ACR_LOGIN_SERVER%%.azurecr.io}" -o table

      # - name: Get AKS creds
      #   run: az aks get-credentials -g <resource-group> -n <aks-name> --overwrite-existing
      # - name: kubectl apply
      #   run: kubectl apply -f k8s/
