name: Backend CD - Deploy to AKS

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to deploy (leave blank to use latest CI SHA)"
        required: false
  workflow_run:
    workflows: [ "Backend CI - Test, Build and Push Images to ACR" ]
    types: [ "completed" ]
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Run on manual trigger OR when CI completed successfully
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    env:
      ACR_LOGIN_SERVER: s722acr84438.azurecr.io
      NAMESPACE: default
      ORDER_DEPLOY: order-service-w08e1
      PRODUCT_DEPLOY: product-service-w08e1
      ORDER_CONTAINER: order-service-container
      PRODUCT_CONTAINER: product-service-container
      SUB_ID: 3ec3f453-a0b9-4c9e-81d1-fc985be293b5
      TAG: ${{ inputs.tag || github.event.workflow_run.head_sha || github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set subscription
        run: az account set --subscription "$SUB_ID"

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RG }}
          cluster-name:  ${{ secrets.AKS_NAME }}

      - name: Patch images to the new tag
        run: |
          set -e
          kubectl set image -n "$NAMESPACE" deploy/$ORDER_DEPLOY   $ORDER_CONTAINER=$ACR_LOGIN_SERVER/week08/order-service:$TAG
          kubectl set image -n "$NAMESPACE" deploy/$PRODUCT_DEPLOY $PRODUCT_CONTAINER=$ACR_LOGIN_SERVER/week08/product-service:$TAG

      - name: Wait for rollout
        run: |
          kubectl rollout status -n "$NAMESPACE" deploy/$ORDER_DEPLOY
          kubectl rollout status -n "$NAMESPACE" deploy/$PRODUCT_DEPLOY

      - name: Show deployed images
        run: |
          kubectl get deploy -n "$NAMESPACE" \
            -o custom-columns=NAME:.metadata.name,IMAGE:.spec.template.spec.containers[0].image,READY:.status.readyReplicas
