name: Backend CI - Test, Build and Push Images to ACR

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  test_build_push:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: s722acr84438
      ACR_LOGIN_SERVER: s722acr84438.azurecr.io
      TAG: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Azure context (debug)
        run: |
          set -e
          az account show
          az acr show -n "$ACR_NAME" -o table

      - name: List repo tree and Dockerfiles (debug)
        run: |
          set -e
          echo "==== REPO TREE (first 200 lines) ===="
          ls -la
          find . -maxdepth 3 -type f -iname Dockerfile -print | nl

      - name: Resolve Dockerfile paths (prefer canonical paths)
        id: paths
        shell: bash
        run: |
          set -e
          # Preferred week08 layout
          ORDER="backend/order-service/Dockerfile"
          PROD="backend/product-service/Dockerfile"

          # Fall back to auto-discovery if missing
          [[ -f "$ORDER" ]] || ORDER=$(find . -type f -iname Dockerfile -path '*order*'   | head -n1)
          [[ -f "$PROD"  ]] ||  PROD=$(find . -type f -iname Dockerfile -path '*product*' | head -n1)

          echo "ORDER_DF=$ORDER"
          echo "PRODUCT_DF=$PROD"

          [[ -n "$ORDER" && -f "$ORDER" ]] || { echo "ERROR: Order Dockerfile not found"; exit 1; }
          [[ -n "$PROD"  && -f "$PROD"  ]] || { echo "ERROR: Product Dockerfile not found"; exit 1; }

          echo "order=$ORDER"  >> "$GITHUB_OUTPUT"
          echo "product=$PROD" >> "$GITHUB_OUTPUT"

      - name: Build & push order-service
        run: |
          az acr build -r "$ACR_NAME" \
            -t week08/order-service:${TAG} \
            -f "${{ steps.paths.outputs.order }}" \
            "$(dirname "${{ steps.paths.outputs.order }}")"

      - name: Build & push product-service
        run: |
          az acr build -r "$ACR_NAME" \
            -t week08/product-service:${TAG} \
            -f "${{ steps.paths.outputs.product }}" \
            "$(dirname "${{ steps.paths.outputs.product }}")"

      - name: Output image URIs
        run: |
          echo "$ACR_LOGIN_SERVER/week08/order-service:${TAG}"
          echo "$ACR_LOGIN_SERVER/week08/product-service:${TAG}"
