name: Backend CD - Deploy to AKS

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-deploy
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy backend to AKS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Login to Azure (uncomment when secrets are configured)
      # - uses: azure/login@v2
      #   with:
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Deploy (placeholder)
        run: |
          echo "Deploying backend because backend/** changed on main."
          # kubectl/helm commands go here
